### ISSUE TITLE
"hugo --source=. --destination=export" encounter error

### ISSUE THREAD

**Issue by luckypoem** [bep/bepsays.com#1]
hi.

root@localhost:/usr/local/hugo-site/examples/bepsays.com# ls
archetypes  config.toml  deploy.sh  gulp         i18n     package.json  script
assets      content      dev.sh     gulpfile.js  layouts  README.md     static
root@localhost:/usr/local/hugo-site/examples/bepsays.com# hugo --source=. --destination=export
Started building sites ...
ERROR 2017/04/22 16:54:49 Error while rendering "page": template: /usr/local/hugo-site/examples/bepsays.com/layouts/_default/single.html:8:7: executing "/usr/local/hugo-site/examples/bepsays.com/layouts/_default/single.html" at <partial "head.html" ...>: error calling partial: Partial "head.html" not found
root@localhost:/usr/local/hugo-site/examples/bepsays.com#

how to fix it?

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
